import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";

const fuente = Roboto({
  style: ["normal"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clinica Dental Dra. Ingrid Abreu",
  description: "Generated by create next app",
  icons: {
    icon: "/ClinicaDentalIngrid_Icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ES">
      <body
        className={fuente.className}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
