import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import FooterPage from "@/components/FooterPage";
import SocialMedia from "@/components/SocialMedia";

const fuente = Roboto({
  style: ["normal"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clinica Dental Dra. Ingrid Abreu",
  description: "Generated by create next app",
  icons: {
    icon: "/ClinicaDentalIngrid_Icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ES">
      <body
        className={`${fuente.className} flex flex-col min-h-screen`}
      >
        <NavBar />
        <main className="flex-grow">
          {children}
        </main>
        <SocialMedia/>
        <FooterPage/>
      </body>
    </html>
  );
}
